//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



internal partial class ZFDataContext : Microsoft.SharePoint.Linq.DataContext {
	
	#region Extensibility Method Definitions
	partial void OnCreated();
	#endregion
	
	public ZFDataContext(string requestUrl) : 
			base(requestUrl) {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="PurchasingStoresRequests")]
	public Microsoft.SharePoint.Linq.EntityList<PurchasingStoresRequestsItem> PurchasingStoresRequests {
		get {
			return this.GetList<PurchasingStoresRequestsItem>("PurchasingStoresRequests");
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Item", Id="0x01")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(PurchasingStoresRequestsItem))]
internal partial class Item : Microsoft.SharePoint.Linq.ITrackEntityState, Microsoft.SharePoint.Linq.ITrackOriginalValues, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
	
	private System.Nullable<int> _id;
	
	private System.Nullable<int> _version;
	
	private string _path;
	
	private Microsoft.SharePoint.Linq.EntityState _entityState;
	
	private System.Collections.Generic.IDictionary<string, object> _originalValues;
	
	private string _title;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion

	Microsoft.SharePoint.Linq.EntityState Microsoft.SharePoint.Linq.ITrackEntityState.EntityState {
		get {
			return this._entityState;
		}
		set {
			if ((value != this._entityState)) {
				this._entityState = value;
			}
		}
	}

	System.Collections.Generic.IDictionary<string, object> Microsoft.SharePoint.Linq.ITrackOriginalValues.OriginalValues {
		get {
			if ((null == this._originalValues)) {
				this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
			}
			return this._originalValues;
		}
	}
	
	public Item() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ID", Storage="_id", ReadOnly=true, FieldType="Counter")]
	public System.Nullable<int> Id {
		get {
			return this._id;
		}
		set {
			if ((value != this._id)) {
				this.OnPropertyChanging("Id", this._id);
				this._id = value;
				this.OnPropertyChanged("Id");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="owshiddenversion", Storage="_version", ReadOnly=true, FieldType="Integer")]
	public System.Nullable<int> Version {
		get {
			return this._version;
		}
		set {
			if ((value != this._version)) {
				this.OnPropertyChanging("Version", this._version);
				this._version = value;
				this.OnPropertyChanged("Version");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileDirRef", Storage="_path", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
	public string Path {
		get {
			return this._path;
		}
		set {
			if ((value != this._path)) {
				this.OnPropertyChanging("Path", this._path);
				this._path = value;
				this.OnPropertyChanged("Path");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Title", Storage="_title", Required=true, FieldType="Text")]
	public virtual string Title {
		get {
			return this._title;
		}
		set {
			if ((value != this._title)) {
				this.OnPropertyChanging("Title", this._title);
				this._title = value;
				this.OnPropertyChanged("Title");
			}
		}
	}
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	protected virtual void OnPropertyChanged(string propertyName) {
		if ((null != this.PropertyChanged)) {
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	protected virtual void OnPropertyChanging(string propertyName, object value) {
		if ((null == this._originalValues)) {
			this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
		}
		if ((false == this._originalValues.ContainsKey(propertyName))) {
			this._originalValues.Add(propertyName, value);
		}
		if ((null != this.PropertyChanging)) {
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Item", Id="0x01", List="PurchasingStoresRequests")]
internal partial class PurchasingStoresRequestsItem : Item {
	
	private string _dept;
	
	private string _requestBatchGuid;
	
	private string _itemGeneralName;
	
	private string _itemSpecificName;
	
	private System.Nullable<double> _quantity;
	
	private string _notes;
	
	private string _status;
	
	private string _empArabicName;
	
	private System.Nullable<int> _empId;
	
	private string _empTitle;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public PurchasingStoresRequestsItem() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Dept", Storage="_dept", FieldType="Text")]
	public string Dept {
		get {
			return this._dept;
		}
		set {
			if ((value != this._dept)) {
				this.OnPropertyChanging("Dept", this._dept);
				this._dept = value;
				this.OnPropertyChanged("Dept");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="RequestBatchGuid", Storage="_requestBatchGuid", FieldType="Text")]
	public string RequestBatchGuid {
		get {
			return this._requestBatchGuid;
		}
		set {
			if ((value != this._requestBatchGuid)) {
				this.OnPropertyChanging("RequestBatchGuid", this._requestBatchGuid);
				this._requestBatchGuid = value;
				this.OnPropertyChanged("RequestBatchGuid");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ItemGeneralName", Storage="_itemGeneralName", FieldType="Text")]
	public string ItemGeneralName {
		get {
			return this._itemGeneralName;
		}
		set {
			if ((value != this._itemGeneralName)) {
				this.OnPropertyChanging("ItemGeneralName", this._itemGeneralName);
				this._itemGeneralName = value;
				this.OnPropertyChanged("ItemGeneralName");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ItemSpecificName", Storage="_itemSpecificName", FieldType="Text")]
	public string ItemSpecificName {
		get {
			return this._itemSpecificName;
		}
		set {
			if ((value != this._itemSpecificName)) {
				this.OnPropertyChanging("ItemSpecificName", this._itemSpecificName);
				this._itemSpecificName = value;
				this.OnPropertyChanged("ItemSpecificName");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Quantity", Storage="_quantity", Required=true, FieldType="Number")]
	public System.Nullable<double> Quantity {
		get {
			return this._quantity;
		}
		set {
			if ((value != this._quantity)) {
				this.OnPropertyChanging("Quantity", this._quantity);
				this._quantity = value;
				this.OnPropertyChanged("Quantity");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Notes", Storage="_notes", FieldType="Text")]
	public string Notes {
		get {
			return this._notes;
		}
		set {
			if ((value != this._notes)) {
				this.OnPropertyChanging("Notes", this._notes);
				this._notes = value;
				this.OnPropertyChanged("Notes");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Status", Storage="_status", FieldType="Text")]
	public string Status {
		get {
			return this._status;
		}
		set {
			if ((value != this._status)) {
				this.OnPropertyChanging("Status", this._status);
				this._status = value;
				this.OnPropertyChanged("Status");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EmpArabicName", Storage="_empArabicName", FieldType="Text")]
	public string EmpArabicName {
		get {
			return this._empArabicName;
		}
		set {
			if ((value != this._empArabicName)) {
				this.OnPropertyChanging("EmpArabicName", this._empArabicName);
				this._empArabicName = value;
				this.OnPropertyChanged("EmpArabicName");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Title {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Item.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Item.");
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Emp", Storage="_empId", Required=true, FieldType="User", IsLookupId=true)]
	public System.Nullable<int> EmpId {
		get {
			return this._empId;
		}
		set {
			if ((value != this._empId)) {
				this.OnPropertyChanging("EmpId", this._empId);
				this._empId = value;
				this.OnPropertyChanged("EmpId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Emp", Storage="_empTitle", ReadOnly=true, FieldType="User", IsLookupValue=true)]
	public string EmpTitle {
		get {
			return this._empTitle;
		}
		set {
			if ((value != this._empTitle)) {
				this.OnPropertyChanging("EmpTitle", this._empTitle);
				this._empTitle = value;
				this.OnPropertyChanged("EmpTitle");
			}
		}
	}
}
